### ISSUE TITLE
Using in React Typescript

### ISSUE THREAD

**Issue by ethersnet** [AdamVig/battery-indicator-element#160]
Hi, I was wondering whether there was a way to use this as a react component rather than a html tag. I tried importing BatteryIndicator from 'battery-indicator-element', but I get the issue that is has no call or construct signatures. Thank you for your time!

**Comment by AdamVig** [comment]
Hi there, thanks for asking. No, there is no way to use this as a React component rather than an HTML tag. If you take a look at [`main.ts`](https://github.com/AdamVig/battery-indicator-element/blob/cbfb880c4742fb2668350f8a1852e3fad61018e7/src/battery-indicator.ts#L8), you'll see that there is no default export, which is why the import statement that you tried wouldn't work.

I use this element within a React app and it works great. I'm not sure if this will address your use-case, but here's a code sample that shows how I use it. The sample is in TypeScript, so if you're using JavaScript, you can ignore the middle section.
```typescript
import 'battery-indicator-element';
import { DetailedHTMLProps, HTMLAttributes } from 'react';

interface BatteryIndicatorProps
	extends DetailedHTMLProps<HTMLAttributes<HTMLElement>, HTMLElement> {
	percentage: number;
}
declare global {
	namespace JSX {
		interface IntrinsicElements {
			'battery-indicator': BatteryIndicatorProps;
		}
	}
}

function Component() {
	return <battery-indicator percentage={95}></battery-indicator>;
}
```

I hope this helps!

**Comment by AdamVig** [comment]
I'm going to go ahead and close this since I have not heard back from you, but please feel free to comment here if you have any other questions.

**Comment by ethersnet** [comment]
Thanks, I got it working!
